[versions]
agp = "8.7.2"
xposed = "82"

[libraries]
xposedapi = { module = "de.robv.android.xposed:api", version.ref = "xposed" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
